name: Build CI

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Build CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile

      - run: pnpm lint
      - run: pnpm build
